services:
  - type: web
    name: peladahub
    env: docker
    healthCheckPath: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
